# Generated by Django 6.0.1 on 2026-04-29 06:49

import django.db.models.deletion
import martor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa fisica'), ('PJ', 'Pessoa juridica')], default='PF', max_length=2)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Contrato'), ('P', 'Petição'), ('CONT', 'Contestação'), ('R', 'Recursos'), ('O', 'Outro')], default='O', max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_upload', models.DateTimeField()),
                ('content', martor.models.MartorField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
        ),
    ]
